name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (continue on error)
      run: npm run lint || true

    - name: Run TypeScript type check
      run: npm run typecheck

    - name: Run tests
      run: npm run test:run

    - name: Build project
      run: npm run build

  functions-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./functions/package-lock.json

    - name: Install functions dependencies
      run: npm ci

    - name: Build functions
      run: npm run build

    - name: Run functions lint
      run: npm run lint